room-luxe-amenities
Yaroslav-Marinich/mi-6 pull request #37
Opened 2022-12-11 17:05 UTC by DimaPo5

2022-12-11 18:02 UTC, Yaroslav-Marinich requested changes
виправ поки все це, потім далі буду дивитись для інших розширень

2022-12-11 18:49 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    font-family: 'Montserrat';
фонт-фемілі іде від боді, не дублюй стилі

2022-12-11 18:51 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    text-decoration: none;
перевір що є в резеті, не дублюй стилі

2022-12-11 18:52 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +    <a href="#" class="link__amenities"
встав лінк на сторінку готелю

2022-12-11 19:06 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +        <use href="/src/images/sprite.svg#icon-cil_arrow-right32"></use>
щось коїться із іконкою на таблеті, на розмірі 1024 у неї неадекватні розміри

2022-12-11 19:06 UTC, Yaroslav-Marinich requested changes
допрацюй

2022-12-11 21:04 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
проблема лишається та сама. не звертайся із секції до контейнера. У контейнера є падінги, вони в компонентах. Дай класу секції amenities__section верхні та нижні падінги, і видали їх із amenities__lines.

2022-12-11 21:06 UTC, Yaroslav-Marinich requested changes
нічого не виправив, дороби

2022-12-11 21:07 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
зараз виправляю

2022-12-11 21:24 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
я змінив

2022-12-11 21:26 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
ти все ще звертаешся до контейнера тут  &__section .container

2022-12-11 21:27 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +        @include desktop {
після таблету стилі залишаються, не дублюй непотрібні стилі

2022-12-11 21:28 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
навіщо тобі весь цей блок, якщо ти вже нижче переназвав блок секції. видали з 3 по 7 лінію

2022-12-11 21:29 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__section .container {
видали .container і видали падінги, залиш тільки колір фону

2022-12-11 21:30 UTC, Yaroslav-Marinich requested changes
виправи по всіх коментарях, не роби пул реквест після кожної дії

2022-12-11 21:34 UTC, Yaroslav-Marinich commented
якщо хочеш, можемо в діскорді зізвонитись, я проговорю тобі всі проблеми що по секції вилізли

2022-12-11 21:47 UTC, Yaroslav-Marinich commented
і будь ласка називай коміти більш конкретніше, вони всі у тебе однієї назви

2022-12-11 21:51 UTC, DimaPo5 commented
Ярослав, які в мене ще бока, потрібно в дискорді зізванюватися

2022-12-11 21:51 UTC, DimaPo5 commented
глянь мою секцію

2022-12-11 23:51 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +        @extend .amenities__discription;
розділи їх, у тебе через їх об'єднання між блоками лишній падінг виліз

2022-12-11 23:56 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +          <p class="amenities__discription">
ти знову відштовхуєш не сусідній елемент, сусідніми елементами тут є <li>, дай їм клас і йому вже присвой марджин.

2022-12-12 00:18 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +    <button class="button" data-modal-open>Оформити бронювання</button>
звіряйся з макетом будь ласка, ти прописав тест, а в макеті текст в кнопці капсом, обо копіюй, або прописуй (text-transform: uppercase;)

2022-12-12 00:22 UTC, Yaroslav-Marinich requested changes
доробити по всіх коментарях

2022-12-12 20:30 UTC, DimaPo5 commented
Ярослав подивися мою гилку

2022-12-12 21:00 UTC, Yaroslav-Marinich requested changes
Будь ласка, виправ всі коментарі, і тільки після цього відправляй коміт на код ревью, якщо не розумієш чогось, або потрібна допомога, пиши в діскорд, у нас багато хто допоже тобі.

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin-top: 16px;
навіщо цей марджин, якщо є вже відступ нижній у сусіднього .amenities__discription

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +            <p class="amenities__discription">
все без змін, ти все ще відштовхуєш цім текстом не сусідній елемент. Відштовхування повинні бути тільки у li

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    text-decoration: none;
пофікси, тут все ще без змін

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +    <div class="menu__wrap">
до чого тут назва класу цього? я не бачу тут меню

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    margin-bottom: 32px;
звідки цей падінг? на макеті 20px

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +      <button class="button" data-modal-open>Оформити бронювання</button>
текст на кнопці не відповідає макету, на кнопці повинні бути всі заглавні літери. пропиши тимчасово все заглавними, потім пофіксим компонент кнопки

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +        gap: 16px;
звідки gap 16, на макеті 12

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    font-family: 'Montserrat';
переглянь стилі боді, у тебе тут купа стилів дулюється.

2022-12-12 21:00 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +        <use href="/src/images/sprite.svg#icon-cil_arrow-right32"></use>
питання все ще відкрито, будь ласка дивись на лайв сторінку коли працюєш

2022-12-12 21:05 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin-top: 16px;
mobimax-413px
mobile-414px

2022-12-12 21:11 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin-top: 16px;
подивись на лайв сторінку, у тебе марджини накладаються

2022-12-13 19:02 UTC, DimaPo5 commented
li з низ

2022-12-14 20:33 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +.amenities {
верхні та нижні падінги загубив)

2022-12-14 20:35 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +.amenities {
падінги всього блоку

2022-12-14 20:37 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin: 0 auto 32px;}
нижній марджин у кнопки 20

2022-12-14 20:38 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin: 0 auto 32px;}
давай в голосовий

2022-12-14 20:39 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +            margin-bottom: 32px;
цей нижній марджин повинен бути у секції

2022-12-14 20:44 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    &__box {
як я і казав, напиши цей клас так &__box:not(:last-child), а потім дай класу amenities__items нижній марджин 32px

2022-12-14 20:47 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +        @include tablet {
на таблеті кнопка поїхала вправо

2022-12-14 20:52 UTC, Yaroslav-Marinich commented on src/partials/pages/room-luxe/amenities.html
> +<section class="amenities">
додай сюди через пробіл клас section-hotel--lemon , у тебе повинен бути фон цього кольору

2022-12-14 20:53 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +    @include desktop {
цей клас вже є, там на всіх версіях повинен бути такий колір, клас називається section-hotel--lemon

2022-12-14 20:54 UTC, DimaPo5 commented on src/sass/pages/room-luxe/_amenities.scss
> +    @include desktop {
куди це

2022-12-14 20:58 UTC, Yaroslav-Marinich requested changes
допрацювати

2022-12-15 00:52 UTC, Yaroslav-Marinich commented on src/sass/pages/room-luxe/_amenities.scss
> +.amenities {
знову те саме......у секції верхні і нижні, у контейнера праві і ліві.....я сам поправлю

2022-12-15 01:11 UTC, Yaroslav-Marinich approved these changes
вибач, але я не витримав і сам все виправив вже, купу разів казав про відступи і ти продовжуєш повторювати помилки

2022-12-15 01:11 UTC, merged