Feature/details restaurant
Yaroslav-Marinich/mi-6 pull request #41
Opened 2022-12-11 23:04 UTC by katushka211

Add section details of our restaurant

2022-12-11 23:32 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.detail-rest__slider {
на макеті слайдер як і іконки відступає більше, спробуй дати йому лівий падінг 26 px

2022-12-11 23:34 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.slick-next:before,
чомусь відображається не білий колір стрілки, вона якась сіра вийшла

2022-12-11 23:38 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.details-rest__wrap {
в таблет версії дуже великий відступ вийшов, звірся з макетом

2022-12-11 23:40 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.details-rest__logo {
у таблет версії змінюється [шрифт лого ](font-size: 64px;)

2022-12-11 23:44 UTC, Yaroslav-Marinich requested changes
допрацювати

2022-12-11 23:54 UTC, katushka211 commented on src/sass/layout/_details-restaurant.scss
> +.details-rest__logo {
змінила

2022-12-12 00:26 UTC, Yaroslav-Marinich requested changes
зміни не підтягнулись

2022-12-12 02:01 UTC, katushka211 commented
fixed baggs

2022-12-12 08:11 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.details-rest__wrap {
тепер в мобайл версії поплив відступ, сильно вліво поїхало

2022-12-12 08:15 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-restaurant.scss
> +.details-rest__wrap {
і в десктоп версії також лівіше поїхав ніж потрібно

2022-12-12 08:15 UTC, Yaroslav-Marinich requested changes
допрацювати один комент по .details-rest__wrap

2022-12-12 09:27 UTC, katushka211 commented
виправлено

2022-12-12 09:38 UTC, Yaroslav-Marinich commented on src/partials/details-restaurant.html
> +          <picture>
відразу не звернув увагу, картинка трохи стиснута ця вийшла

2022-12-12 09:39 UTC, Yaroslav-Marinich requested changes
відразу не побачив, третя картинка вийшла стиснута

2022-12-12 10:56 UTC, katushka211 commented on src/partials/details-restaurant.html
> +          <picture>
виправлено

2022-12-12 11:02 UTC, Yaroslav-Marinich approved these changes

2022-12-12 11:02 UTC, merged