Features/about our kitchen
Yaroslav-Marinich/mi-6 pull request #44
Opened 2022-12-12 19:18 UTC by YevgeniyaAndriyevskaya

Finished restaurant page kitchen section. 
Can't resolve merge issue from my end.

2022-12-12 19:21 UTC, YevgeniyaAndriyevskaya commented
Fixed merging issue in slider.js

2022-12-12 19:46 UTC, Yaroslav-Marinich requested changes
Я пояснював, в цій зборці нам не потрібно натискати Watch Sass, воно створює купу непотрібних нам файлів. лишні файли видалю сам

2022-12-12 20:01 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +// VERTICAL SECTION STRIPES
Ми вирішили що ці лінії тільки для макету, вони не вписуються в сайт, тим паче що вони всі криві та ломані, на кожній секції різні. Тож видали їх

2022-12-12 20:08 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +.restaurant-logo {
в компонентах є _logo.scss, пропиши його клас та перебий непідходящі тобі стилі. Ми ж робили ці компоненти не просто так

2022-12-12 20:12 UTC, Yaroslav-Marinich commented on src/partials/pages/restaurant/about-kitchen.html
> +          <source
картинка на мобайлі не співпадає розміром

2022-12-12 20:14 UTC, Yaroslav-Marinich commented on src/partials/pages/restaurant/about-kitchen.html
> +      <div class="kitchen-card">
передивись весь блок, на мобайл версії він поплив

2022-12-12 20:16 UTC, Yaroslav-Marinich commented on src/partials/pages/restaurant/about-kitchen.html
> +    <div class="kitchen-slider-box">
побачив неприємну річ, на слайдері є тінь, а між картками її нема, і вон дуже сильно кидається у вічі. Спробуйте зробити у слайдера бекграунд колор прозорий

2022-12-12 20:27 UTC, Yaroslav-Marinich commented on src/partials/pages/restaurant/about-kitchen.html
> +    <div class="kitchen-slider-box">
Також відступи між картками не співпадають із макетом

2022-12-12 20:55 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +// VERTICAL SECTION STRIPES
Удалила в html & css.

2022-12-12 21:01 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +.restaurant-logo {
Добавила компонентный класс в html.
Удалила дублирующиеся свойства.
Необходимые мне дополнительные свойства добавила через класс .restaurant-logo

2022-12-12 21:21 UTC, YevgeniyaAndriyevskaya commented on src/partials/pages/restaurant/about-kitchen.html
> +          <source
Исправила. Из-за того, что соседний текст растянулся и ужал мою картинку. 
Задала тексту max-width как по макету - и все стало на свои места.

2022-12-12 21:21 UTC, YevgeniyaAndriyevskaya commented on src/partials/pages/restaurant/about-kitchen.html
> +      <div class="kitchen-card">
Исправила. Из-за того, что соседний текст растянулся и ужал мою картинку.
Задала тексту max-width как по макету - и все стало на свои места.
Изменила контейнеру секции нижний паддинг, чтобы совпало с макетом.

2022-12-12 22:08 UTC, YevgeniyaAndriyevskaya commented on src/partials/pages/restaurant/about-kitchen.html
> +    <div class="kitchen-slider-box">
Тут при сборке сломалось, так как мне подтянулся еще и gap из другой секции. 
Обратилась сама через .slick-track , написала gap с макета и убрала правый марджин для слайдов.
Все заработало.

С тенью... Вот тут я очень долго мучалась сегодня. Как бы у каждого отдельного слайда есть тень, но она не может вылезти за контейнер родителя. А если я контейнеру родителя даю overflow:visible, то ломается весь слайдер.
Потому дала тень и контейнеру слайдера, но тогда дырка некрасиво в gap'ах желтый цвет режет глаза. 
Исправила это добавлением тени каждому слайду.
Теперь если присмотреться есть линия стыковки двух теней, от которой я так и не смогла избавиться.

2022-12-12 22:09 UTC, YevgeniyaAndriyevskaya commented
Закончила фиксы.

2022-12-13 11:49 UTC, Yaroslav-Marinich requested changes
допрацювати по коментах

2022-12-13 11:49 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  .container {
на контейнері повинні бути лише ліві та праві падінги, верхні та нижні даються секції

2022-12-13 11:49 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  line-height: 1.15;
це наслідується від браузера, не дублюй стилі, передивись що ще наслідується та прибери

2022-12-13 11:49 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  font-weight: 400;
для шрифтів у нас є міксин @mixin font в утілках, заміни де можливо

2022-12-13 11:49 UTC, Yaroslav-Marinich commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  background: #dadada;
в змінних є цей колір $colorBgImage

2022-12-13 13:56 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  .container {
перенесла вертикальные паддинги на секцию about-our-kitchen

2022-12-13 14:11 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  line-height: 1.15;
исправила line-height: 1.15 и font-style: normal в .about-kitchen__slogan. Других дубляжей нет

2022-12-13 14:27 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  font-weight: 400;
Заменила в секциях:
.about-kitchen__slogan
.kitchen-card__description

2022-12-13 14:32 UTC, merged

2022-12-13 14:33 UTC, YevgeniyaAndriyevskaya commented on src/sass/pages/restaurant/_about-kitchen.scss
> +  background: #dadada;
Заменила цвет в классе .kitchen-card__photo