feature/modal-room
Yaroslav-Marinich/mi-6 pull request #49
Opened 2022-12-13 10:06 UTC by katushka211

add modal-room

2022-12-13 11:26 UTC, Yaroslav-Marinich requested changes
допрацювати

2022-12-13 11:26 UTC, Yaroslav-Marinich commented on src/sass/components/_modal-room.scss
> +  box-shadow: 2px 2px 15px 2px $colorTextSecondary;
на макеті немає тіні)

2022-12-13 11:26 UTC, Yaroslav-Marinich commented on src/sass/components/_modal-room.scss
> +.modal-room__custom-select {
не по центру іконка

2022-12-13 11:26 UTC, Yaroslav-Marinich commented on src/partials/modal-room.html
> +      <input class="modal-room__modal-input custom-date modal-room__custom-select" type="text" name="arrival-date"
а чому ти тут даєш клас custom-date, а в наступному інпуті modal-room__custom-date, у тебе ж обидва інпути однакові, а у другому навіть іконка нормально підтягнулась

2022-12-13 11:26 UTC, Yaroslav-Marinich commented on src/sass/components/_modal-room.scss
> +.modal-room__modal-label {
глянь які стилі тягне із боді, не дублюй код, як мінімум фонт сайз тягне

2022-12-14 00:47 UTC, katushka211 commented on src/sass/components/_modal-room.scss
> +.modal-room {
виправлено

2022-12-14 00:51 UTC, katushka211 commented on src/sass/components/_modal-room.scss
> +.modal-close {
done

2022-12-14 00:52 UTC, katushka211 commented on src/partials/modal-room.html
> +      <input
додано

2022-12-14 15:40 UTC, Yaroslav-Marinich approved these changes

2022-12-14 15:40 UTC, merged