Feature/details hotel
Yaroslav-Marinich/mi-6 pull request #54
Opened 2022-12-13 15:32 UTC by ArtemFomchenkov

2022-12-13 15:32 UTC, ArtemFomchenkov commented
.

2022-12-13 18:08 UTC, Yaroslav-Marinich requested changes
допрацювати

2022-12-13 18:08 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-hotel.scss
> +      margin-left: 90px;
чому 90? на макеті 197)

2022-12-13 18:08 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-hotel.scss
> +  .details-hotel__logo {
Також з таблету змінюється текст, звіряйся з макетом

2022-12-13 18:08 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-hotel.scss
> +  .details-hotel__text {
Звірся з розширеннями, розмір блоку тексту повинен співпадати

2022-12-14 21:22 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-hotel.scss
> +  .details-hotel__container {
ми це проговорили вже після стендапу, зроби їх 42

2022-12-14 21:25 UTC, Yaroslav-Marinich commented on src/sass/layout/_details-hotel.scss
> +    padding-left: 17px;
а навіщо цей падінг, якщо текст від лівого краю секції відступає на 32, зроби просто для мобайл лівий падінг у секції 32 і все

2022-12-14 22:04 UTC, Yaroslav-Marinich requested changes
доработать, проговорили все

2022-12-15 00:47 UTC, Yaroslav-Marinich approved these changes

2022-12-15 00:47 UTC, merged