Feature/1 room for 2 adult
Yaroslav-Marinich/mi-6 pull request #67
Opened 2022-12-14 17:08 UTC by IgorJurievic

2022-12-14 17:51 UTC, Yaroslav-Marinich requested changes
допрацювати

2022-12-14 17:51 UTC, Yaroslav-Marinich commented on src/sass/pages/hotel/_room-for-2.scss
> +.hotel-room-slider {
Глянь у Влада на слайдер, він у нього як на макеті вийшов. І так само: на сладері є тіні, але уважно, не кидай на весь слайдер, бо тоді між картинками тіні не буде

2022-12-14 17:51 UTC, Yaroslav-Marinich commented on src/sass/pages/hotel/_room-for-2.scss
> +.room-svg {
змісти лівіше стрілки, як на макеті

2022-12-14 17:51 UTC, Yaroslav-Marinich commented on src/partials/pages/hotel/room-for-2.html
> +        <a href="" class="btn btn--hotel-and-rest hotel-link">Детальніше</a>
дай посилання на файл сторінки

2022-12-14 17:51 UTC, Yaroslav-Marinich commented on src/partials/pages/hotel/room-for-2.html
> +<section class="room-section section-hotel section-hotel--lemon">
в таблеті перестарались із нижнім падінгом секції. У влада така ж помилка, тому або перебийте кожен у себе падінги, або хтось один внесіть зміни у компонент секції

2022-12-14 17:51 UTC, Yaroslav-Marinich commented on src/sass/pages/hotel/_room-for-2.scss
> +.room-svg {
на десктопі стрілки зовсім поїхали

2022-12-15 14:31 UTC, IgorJurievic commented on src/partials/pages/hotel/room-for-2.html
> +<section class="room-section section-hotel section-hotel--lemon">
виправив у секції

2022-12-15 14:31 UTC, IgorJurievic commented on src/partials/pages/hotel/room-for-2.html
> +        <a href="" class="btn btn--hotel-and-rest hotel-link">Детальніше</a>
дав

2022-12-15 14:42 UTC, IgorJurievic commented on src/sass/pages/hotel/_room-for-2.scss
> +.room-svg {
виравив

2022-12-15 14:42 UTC, IgorJurievic commented on src/sass/pages/hotel/_room-for-2.scss
> +.room-svg {
поправив

2022-12-15 15:45 UTC, Yaroslav-Marinich approved these changes

2022-12-15 15:45 UTC, merged